import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './components/navbar/Navbar';
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
import AddPropertyModal from "./components/modals/AddPropertModal";
import SearchModal from "./components/modals/SearchModal";
import VideoCallModal from "./components/modals/VideoCallModal";
import CallNotification from "./components/CallNotification";
import { ToastContainer } from "./components/Toast";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RoomsMandu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const contents = (
    <p>
      Welcome to RoomsMandu! Your trusted platform for finding and listing rooms, flats, and properties in Nepal. Enjoy a seamless renting experience with verified listings, easy inquiries, and secure communication between landlords and tenants.
    </p>
  )
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" type="image/png" href="/1.png" />
        {/* Google Translate Widget */}
        <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" async></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              function googleTranslateElementInit() {
                new google.translate.TranslateElement({
                  pageLanguage: 'en',
                  includedLanguages: 'en,ne',
                  layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
                  autoDisplay: false
                }, 'google_translate_element');
              }
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />

        <div className="pt-45">
        {children}
        </div>

        <LoginModal />
        <SignupModal />
        <AddPropertyModal />
        <SearchModal />
        <VideoCallModal />
        <CallNotification />
        <ToastContainer />

        {/* <Modal 
          label="Modal Test"
          content={contents}
          isOpen={false} 
          /> */}
      </body>
    </html>
  );
}
